issues/208
V4Fire/Core pull request #209
Opened 2021-07-08 09:29 UTC by agent-bo-007

2021-07-09 09:01 UTC, Razdva122 commented on src/core/log/middlewares/filter/README.md
> +    check: (event) => { /* Return true or false */ }
Return boolean?

2021-07-09 09:29 UTC, Razdva122 commented on src/core/log/middlewares/filter/README.md
> +## How ot use
```suggestion
## How to use
```

2021-07-09 13:52 UTC, bonkalol commented on src/core/log/middlewares/filter/modules/duplicates-filter.ts
> +	protected readonly errorsMap: WeakMap<Error, 1> = new WeakMap();
А почему не WeakSet?

2021-07-11 23:28 UTC, ExactlyNoSense requested changes

2021-07-11 23:28 UTC, ExactlyNoSense commented on src/core/log/config/options.ts
> +interface LogOptions {
Кажется, это интерфейс должен экспортироваться наружу. И интерфейсы лежат в отдельных файлах `interface.ts`

2021-07-11 23:28 UTC, ExactlyNoSense commented on src/core/log/config/options.ts
> +export function getLogOptions(): typeof logOps {
Почему возвращается `typeof logOps`, когда есть готовый интерфейс?

2021-07-11 23:28 UTC, ExactlyNoSense commented on src/core/log/middlewares/filter/README.md
> +## Existing filters
Available filters звучит лучше

2021-07-11 23:28 UTC, ExactlyNoSense commented on src/core/log/middlewares/filter/filter.ts
> +	protected readonly filters: LogFilter[] = [];
Нет коммента

2021-07-11 23:28 UTC, ExactlyNoSense commented on src/core/log/middlewares/filter/index.ts
> +export { FilterMiddleware } from 'core/log/middlewares/filter/filter';
Тут можно заэкспортить фильтры

2021-07-11 23:28 UTC, ExactlyNoSense commented on src/core/log/middlewares/filter/modules/duplicates-filter.ts
> +	protected readonly errorsMap: WeakSet<Error> = new WeakSet();
Не хватает коммента

2021-07-11 23:28 UTC, ExactlyNoSense commented on src/core/log/middlewares/filter/modules/duplicates-filter.ts
> + * Removes duplicated events
Фильтр отфильтровывает ивенты, а не удаляет их

2021-07-11 23:28 UTC, ExactlyNoSense commented on src/core/log/middlewares/initialization-queue.ts
> +export class InitializationQueueMiddleware implements LogMiddleware {
Очень странное разбиение на классы.

Раньше была одна мидлвара `configurable`, которая знала о существовании настроек фильтрации и внутри себя умела прихранивать логируемые события в очередь, пока настройки асинхронно не получат значение. Т.е. все знания об очереди, асинхронности и зависимой от этого фильтрации инкапсулировались в одной сущности, которая об этом знала и умела обрабатывать. Убираешь эту мидлвару из настроек, и всё продолжат работать, как надо.

Теперь же ты разделил наполнение очереди и саму фильтрацию по разным сущностям. И более того, теперь они связаны неявно. Если я захочу убрать фильтрацию по контексту, то мне нужно ещё догадаться, что `initializationQueue` тоже больше не нужна. Если я хочу добавить фильтрацию, то мне нужно знать, что оказывается я могу пропустить какие-то ивенты, и поэтому для нормальной работы конкретно этого фильтра мне нужно добавить ещё одну мидлвару. В общем, теперь процесс настройки стал неочевидным

2021-07-11 23:28 UTC, ExactlyNoSense commented on src/core/log/middlewares/initialization-queue.ts
> + * Middleware to store events until the logging config is initialized
Единственное место, где появляется определение `logging config`. Как теперь понять, что это такое?

2021-07-11 23:28 UTC, ExactlyNoSense commented on src/core/log/middlewares/filter/README.md
> +## How to use
Тут бы не помешало сказать, в каком порядке будут вызываться переданные в мидлвару фильтры

2021-07-12 07:53 UTC, agent-bo-007 commented on src/core/log/middlewares/initialization-queue.ts
> +export class InitializationQueueMiddleware implements LogMiddleware {
Ну если рассматривать частный случай, то да. Но мы вроде находимся в опенсорсе. И что делать для проектов, где у тебя опции логирования заданы сразу, и не требуют ожидания инициализации? И с этой точки зрения сразу видно, что у `configurable` еще и нарушен принцип единственной ответственности. Фильтрация событий, и очередь ожидания - это все-таки разные вещи, и тут сложно прикрыться тем, что мидла отвечает целиком за работу с конфигом. Ожидать возможности логировать события можно и не только из-за инициализации конфига. Придется тогда еще 1 мидлу с очередью пилить?

2021-07-12 08:11 UTC, agent-bo-007 commented on src/core/log/middlewares/initialization-queue.ts
> + * Middleware to store events until the logging config is initialized
ну тут к тебе скорее вопрос, потому что я тоже не очень понимаю) Для инициализации `logOps` использовалась функция `setConfig` - отсюда и метания в названиях. И еще я не совсем был уверен на счет `logOps`  - это отсылка к https://github.com/telefonicaid/logops? Или все-таки `logOpts`? Или `logConfig`? Хз

2021-08-31 09:25 UTC, closed without merging