first
V4Fire/Core pull request #305
Opened 2022-06-27 11:52 UTC by kz2d

2022-06-27 12:05 UTC, kobezzza commented on src/core/request/spec.js
> +			it('RequestErrorDetailsExtractor, include and exclude specific header', async () => {
Тут какая то беда с отступами

2022-06-28 07:03 UTC, ExactlyNoSense requested changes

2022-06-28 07:03 UTC, ExactlyNoSense commented on src/core/request/spec.js
> +			it('RequestErrorDetailsExtractor, include and exclude specific header', async () => {
Не очень понимаю, зачем эти тесты запихивать в тесты request. Такими темпами они превратятся в какую-то свалку всего подряд.

На мой взгляд, лучше сделать отдельный файл для тестов экстрактора и проверять разные сценарии отдельно.

Сейчас тесты написаны ненадёжно и проверяют какую-то выборочную информацию.

Первая проблема: ты используешь один и тот же объект ошибки для разных экстракторов. Т.к. объекты передаются по ссылке, то ты по сути делаешь результаты проверок зависимыми от последовательности выполнения разных экстракторов и снижаешь их надёжность. Т.е. в самом худшем случае после каких-нибудь правок тесты могут стать ложно положительными. Самое главное в написании тестов - их независимость друг от друга.

Вторая проблема: из тестов непонятно какие заголовки есть изначально, и какие изменения в итоге делают экстракторы. В тестах должно быть явно видно 3 вещи: входные данные, выполнение тестируемого кода, результат.

Третья проблема: проверяются только заголовоки. Если произойдёт какая-то бага в других полях, то мы этого опять же не увидим. Тесты должны фиксировать контракт, и возвращаемые детали ошибки - это и есть контракт экстрактора

2022-07-05 12:39 UTC, ExactlyNoSense approved these changes

2022-07-05 15:15 UTC, merged