feat: add .redirect to RequestOptions and support in fetch engine
V4Fire/Core pull request #448
Opened 2024-11-06 09:43 UTC by kormanowsky

2024-11-15 07:32 UTC, gretzkiy commented
В движке xhr тоже нужно поддержать, если возможно

2024-11-15 07:35 UTC, gretzkiy requested changes
В движке xhr тоже нужно поддержать, если возможно

2024-11-15 12:54 UTC, kormanowsky commented
@gretzkiy 

Не нашел возможности поддержки такого в XHR. 
Плюс даже с fetch() это по-разному работает в браузере и в ноде. 
Сейчас предполагается использовать только в ноде, так как там в случае redirect manual можно прочитать заголовки ответа, а в браузере - нет. А в ноде XHR по дефолту нет. 
Поэтому кажется это и не нужно там?

2024-11-21 08:28 UTC, gretzkiy approved these changes

2024-11-21 12:08 UTC, shining-mind approved these changes
Только CHANGELOG надо заполнить

2024-12-02 08:36 UTC, merged